// Persona types for AI questioner
export type Persona = 'skeptical' | 'expert' | 'confused' | 'adversarial'

// Question delivery modes
export type DeliveryMode = 'interrupt' | 'queue' | 'hybrid'

// Question types
export type QuestionType =
  | 'clarification'
  | 'technical'
  | 'conceptual'
  | 'methodology'
  | 'adversarial'
  | 'bigPicture'

// Urgency levels
export type Urgency = 'interrupt' | 'queue'

// Slide representation
export interface Slide {
  number: number
  textContent: string
  visualDescription: string
}

// Transcript segment
export interface TranscriptSegment {
  text: string
  timestamp: number
  slideNumber: number
}

// Question generated by AI
export interface Question {
  id: string
  text: string
  type: QuestionType
  urgency: Urgency
  trigger: string
  slideRef: number
  answered: boolean
  response?: string
}

// Session settings
export interface SessionSettings {
  persona: Persona
  deliveryMode: DeliveryMode
}

// Full session state
export interface Session {
  id: string
  slides: Slide[]
  transcript: TranscriptSegment[]
  questions: Question[]
  settings: SessionSettings
  startTime: number | null
  endTime: number | null
}

// Type guards
export function isSlide(value: unknown): value is Slide {
  if (typeof value !== 'object' || value === null) return false
  const obj = value as Record<string, unknown>
  return (
    typeof obj.number === 'number' &&
    typeof obj.textContent === 'string' &&
    typeof obj.visualDescription === 'string'
  )
}

export function isTranscriptSegment(value: unknown): value is TranscriptSegment {
  if (typeof value !== 'object' || value === null) return false
  const obj = value as Record<string, unknown>
  return (
    typeof obj.text === 'string' &&
    typeof obj.timestamp === 'number' &&
    typeof obj.slideNumber === 'number'
  )
}

export function isQuestion(value: unknown): value is Question {
  if (typeof value !== 'object' || value === null) return false
  const obj = value as Record<string, unknown>
  const validTypes: QuestionType[] = [
    'clarification',
    'technical',
    'conceptual',
    'methodology',
    'adversarial',
    'bigPicture',
  ]
  const validUrgencies: Urgency[] = ['interrupt', 'queue']
  return (
    typeof obj.id === 'string' &&
    typeof obj.text === 'string' &&
    typeof obj.type === 'string' &&
    validTypes.includes(obj.type as QuestionType) &&
    typeof obj.urgency === 'string' &&
    validUrgencies.includes(obj.urgency as Urgency) &&
    typeof obj.trigger === 'string' &&
    typeof obj.slideRef === 'number' &&
    typeof obj.answered === 'boolean'
  )
}

export function isPersona(value: unknown): value is Persona {
  const validPersonas: Persona[] = ['skeptical', 'expert', 'confused', 'adversarial']
  return typeof value === 'string' && validPersonas.includes(value as Persona)
}

export function isDeliveryMode(value: unknown): value is DeliveryMode {
  const validModes: DeliveryMode[] = ['interrupt', 'queue', 'hybrid']
  return typeof value === 'string' && validModes.includes(value as DeliveryMode)
}

export function isSessionSettings(value: unknown): value is SessionSettings {
  if (typeof value !== 'object' || value === null) return false
  const obj = value as Record<string, unknown>
  return isPersona(obj.persona) && isDeliveryMode(obj.deliveryMode)
}

export function isSession(value: unknown): value is Session {
  if (typeof value !== 'object' || value === null) return false
  const obj = value as Record<string, unknown>
  return (
    typeof obj.id === 'string' &&
    Array.isArray(obj.slides) &&
    obj.slides.every(isSlide) &&
    Array.isArray(obj.transcript) &&
    obj.transcript.every(isTranscriptSegment) &&
    Array.isArray(obj.questions) &&
    obj.questions.every(isQuestion) &&
    isSessionSettings(obj.settings) &&
    (obj.startTime === null || typeof obj.startTime === 'number') &&
    (obj.endTime === null || typeof obj.endTime === 'number')
  )
}
